title = "TideBitEx"

[base]
folder = "CAFECA-framework"
static = "./build/"
TideBitLegacyPath = '/home/ubuntu/TideBit-Lagacy'
debug = false

[blockchain]
type = "ethereum"

# 請參考 https://www.okx.com/docs-v5/broker_zh/#non-disclosed-broker 申請
[okex]
domain = 'https://www.okx.com'
wssPublic = 'wss://ws.okx.com:8443/ws/v5/public'
wssPrivate = 'wss://ws.okx.com:8443/ws/v5/private'
apiKey = ''
secretKey = ''
passPhrase = ''
brokerId = ''

[pusher]
app = 0
key = '' # slanger 的 app_key
secret = '' # slanger 的 secret_key
protocol = 'ws'
host = ''  # slanger 伺服器位址
port = 4567  # slanger REST API port
wsPort = 8080  # slanger 的 WebSocket port
wssPort = 18080  # slanger 的 WSS（WebSockets over SSL/TLS）port
encrypted = false  # slanger 是否啟用 SSL 加密

[peatio]
domain = 'http://127.0.0.1:3000'      # 要與TideBit-Legacy application.yml中URL_HOST相同
systemMemberId = 60976

[redis]
domain = 'redis://127.0.0.1:6379'

[websocket]
domain = 'ws.tidebit.network'

[database]
protocol = 'mysql'
host = '127.0.0.1'
port = '3306'
user = 'user'
password = ''
dbName = ''
logging = false
ormEnable = false
  [database.dialectOptions]
  connectTimeout = 3000
  [database.pool]
  max = 10

[api]
pathname = [
  "get | /version | Static.Utils.readPackageInfo",
  "get | /lacale, /lacale/:language | Static.Utils.getLocaleData",
  
  # exchange - account
  "get | /api/v1/account/balance | Bot.ExchangeHub.getAccounts",

  # exchange - market
  "get | /api/v1/market/options | Bot.ExchangeHub.getOptions",
  "get | /api/v1/market/ticker | Bot.ExchangeHub.getTicker",
  "get | /api/v1/market/tickers | Bot.ExchangeHub.getTickers",
  "get | /api/v1/market/books | Bot.ExchangeHub.getDepthBooks",
  "get | /api/v1/market/candles | Bot.ExchangeHub.getCandlesticks",
  "get | /api/v1/market/trades | Bot.ExchangeHub.getTrades",

  # exchange - trade
  "post | /api/v1/trade/order | Bot.ExchangeHub.postPlaceOrder",
  "get | /api/v1/trade/orders | Bot.ExchangeHub.getOrders",
  "get | /api/v1/trade/orders-pending | Bot.ExchangeHub.getOrderList",
  "get | /api/v1/trade/orders-history | Bot.ExchangeHub.getOrderHistory",
  "post | /api/v1/trade/cancel-order | Bot.ExchangeHub.postCancelOrder",
  "post | /api/v1/trade/cancel-orders | Bot.ExchangeHub.cancelOrders",
  "get | /api/v1/trade/fill-history | Bot.ExchangeHub.getOuterTradeFills",
  "get | /api/v1/trade/profits | Bot.ExchangeHub.getOuterTradesProfits",
  "get | /api/v1/trade/pending-orders | Bot.ExchangeHub.getOuterPendingOrders",


  # exchange - public
  "get | /api/v1/public/instruments | Bot.ExchangeHub.getInstruments",
  "get | /api/v1/public/exchange-rates | Bot.ExchangeHub.getExchangeRates",

  # tradingview
  "get | /api/v1/tradingview/config | Bot.ExchangeHub.getTradingViewConfig",
  "get | /api/v1/tradingview/symbols | Bot.ExchangeHub.getTradingViewSymbol",
  "get | /api/v1/tradingview/history | Bot.ExchangeHub.getTradingViewHistory",

  # UI
  "get | /markets, /markets/:market | Static.Utils.renderMarket",
  "get | /analysis, /analysis | Static.Utils.renderMarket",

  # dashboard
  "get | /api/v1/dashboard | Bot.Dashboard.overview",

  # options

  # exchange - users
  "get | /api/v1/users/account/list | Bot.ExchangeHub.getUsersAccounts",
  "get | /api/v1/users/subaccount/list | Bot.ExchangeHub.getExAccounts",

  # analysis - admin
  "get | /api/v1/admin/admin-users | Bot.ExchangeHub.getAdminUsers",
  "get | /api/v1/admin/admin-users/:id | Bot.ExchangeHub.getAdminUser",
  "post | /api/v1/admin/admin-users | Bot.ExchangeHub.addAdminUser",
  "put | /api/v1/admin/admin-users/:id | Bot.ExchangeHub.updateAdminUser",
  "delete | /api/v1/admin/admin-users/:id | Bot.ExchangeHub.deleteAdminUser",

  "get | /api/v1/admin/coins-settings | Bot.ExchangeHub.getCoinsSettings",
  "put | /api/v1/admin/coins-settings | Bot.ExchangeHub.updateCoinsSettings",
  "put | /api/v1/admin/coins-settings/:id | Bot.ExchangeHub.updateCoinSetting",
  "put | /api/v1/admin/deposits-settings/:id | Bot.ExchangeHub.updateDepositSetting",
  "put | /api/v1/admin/withdraws-settings/:id | Bot.ExchangeHub.updateWithdrawSetting",

  "get | /api/v1/admin/tickers-settings | Bot.ExchangeHub.getTickersSettings",
  "put | /api/v1/admin/tickers-settings/:id | Bot.ExchangeHub.updateTickerSetting",

  "get | /api/v1/admin/platform-assets | Bot.ExchangeHub.getPlatformAssets",
  "put | /api/v1/admin/platform-assets/:id | Bot.ExchangeHub.updatePlatformAsset",
  
  "get | /api/v1/admin/dashboard | Bot.ExchangeHub.getDashboardData",

  "get | /api/v1/logout | Bot.ExchangeHub.logout",
  "get | /api/v1/private/audit-accounts | Bot.ExchangeHub.accountAuditor",

  "get | /api/v1/private/clients | Bot.WSChannel.getPrivateClients"
]