# CAFECA Default Config

title = "TideBitEx"

[base]
folder = "CAFECA-framework"
static = "./public/"
debug = false

[blockchain]
type = "ethereum"

[okex]
domain = 'https://www.okex.com'
apiKey = ''
secretKey = ''
passPhrase = ''

[database]


[api]
pathname = [
  "get | /version | Static.Utils.readPackageInfo",
  "get | /lacale, /lacale/:language | Static.Utils.getLocaleData"
]