# CAFECA Default Config

title = "TideBitEx"

[base]
folder = "CAFECA-framework"
static = "./build/"
debug = false

[blockchain]
type = "ethereum"

[okex]
domain = 'https://www.okx.com'
wssPublic = 'wss://ws.okx.com:8443/ws/v5/public'
apiKey = ''
secretKey = ''
passPhrase = ''
brokerId = ''

[peatio]
domain = 'http://127.0.0.1:3000'

[database]


[api]
pathname = [
  "get | /version | Static.Utils.readPackageInfo",
  "get | /lacale, /lacale/:language | Static.Utils.getLocaleData",

  # exchange - account
  "get | /api/v1/account/balance | Bot.ExchangeHub.getBalance",

  # exchange - market
  "get | /api/v1/market/tickers | Bot.ExchangeHub.getTickers",
  "get | /api/v1/market/books | Bot.ExchangeHub.getOrderBooks",
  "get | /api/v1/market/candles | Bot.ExchangeHub.getCandlesticks",
  "get | /api/v1/market/trades | Bot.ExchangeHub.getTrades",

  # exchange - trade
  "post | /api/v1/trade/order | Bot.ExchangeHub.postPlaceOrder",
  "get | /api/v1/trade/orders-pending | Bot.ExchangeHub.getOrderList",
  "get | /api/v1/trade/orders-history | Bot.ExchangeHub.getOrderHistory",
]